language: java
jdk:
  - oraclejdk8
  - openjdk8
services:
  - postgresql

before_script:
  - psql -c "create database pdf;" -U postgres
  - psql -c "ALTER USER postgres WITH PASSWORD 'postgres';" -U postgres
