#spring:
#  jpa:
#    database: postgresql
#    hibernate:
#      ddl-auto: update
#  datasource:
#    password: postgres
#    username: postgres
#    url: jdbc:postgresql://localhost:5432/pdf
#    driver-class-name: org.postgresql.Driver

spring:
  application:
    name: RenderCountService

  jpa:
    database: h2
  datasource:
    url: jdbc:h2:mem:pdf

eureka:
  client:
    service-url:
      defaultZone:
        ${EUREKA_URI:http://localhost:8761/eureka}
